[package]
name = "ble-over-ip-client"
edition = "2021"
version = "0.1.0"
authors = ["Szymon Piechaczek szymon@piechaczek.it"]

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
clap = { version = "4.5.3", features = ["derive"] }
ble-over-ip-proto = { path = "../proto" }
tonic = "0.11.0"