[package]
name = "ble-over-ip-server"
edition = "2021"
version = "0.1.0"
authors = ["Szymon Piechaczek szymon@piechaczek.it"]

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
uuid = "1.7.0"
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["derive"] }
btleplug = "0.11.5"
prost = "0.12.3"
tonic = "0.11.0"

ble-over-ip-proto = { path = "../proto" }